config/routes.rb
Rails.application.routes.draw do

  resources :etat_civils
  resources :client_etat_civils
  resources :employeurs
  resources :adresses
  resources :institutions
  resources :etudes
  resources :enfants
  resources :clients
  root 'clients#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adresse.rb
class Adresse < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :Adresse_id
end

app/models/client_etat_civil.rb
class ClientEtatCivil < ApplicationRecord
  belongs_to :Client_id
  belongs_to :EtatCivil_id
end

app/models/client_has_conjoint.rb
class ClientHasConjoint < ApplicationRecord
  belongs_to :Client_id
  belongs_to :Client_conjoint_id
end

app/models/client_has_employeur.rb
class ClientHasEmployeur < ApplicationRecord
  belongs_to :Client_id
  belongs_to :Employeur_id
end

app/models/client_has_enfant.rb
class ClientHasEnfant < ApplicationRecord
  belongs_to :Enfant_id
  belongs_to :Client_id
end

app/models/employeur.rb
class Employeur < ApplicationRecord
  belongs_to :Adresse_id
end

app/models/enfant.rb
class Enfant < ApplicationRecord
end

app/models/etat_civil.rb
class EtatCivil < ApplicationRecord
end

app/models/etude.rb
class Etude < ApplicationRecord
  belongs_to :Client_id
  belongs_to :Institution_id
end

app/models/institution.rb
class Institution < ApplicationRecord
  belongs_to :Adresse_id
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:Prenom, :Nom, :DateNaissance, :NAS, :Adresse_id_id, :NombreEnfants, :CompteTaxesProprietaire)
    end
end

app/controllers/etudes_controller.rb
class EtudesController < ApplicationController
  before_action :set_etude, only: [:show, :edit, :update, :destroy]

  # GET /etudes
  # GET /etudes.json
  def index
    @etudes = Etude.all
  end

  # GET /etudes/1
  # GET /etudes/1.json
  def show
  end

  # GET /etudes/new
  def new
    @etude = Etude.new
  end

  # GET /etudes/1/edit
  def edit
  end

  # POST /etudes
  # POST /etudes.json
  def create
    @etude = Etude.new(etude_params)

    respond_to do |format|
      if @etude.save
        format.html { redirect_to @etude, notice: 'Etude was successfully created.' }
        format.json { render :show, status: :created, location: @etude }
      else
        format.html { render :new }
        format.json { render json: @etude.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /etudes/1
  # PATCH/PUT /etudes/1.json
  def update
    respond_to do |format|
      if @etude.update(etude_params)
        format.html { redirect_to @etude, notice: 'Etude was successfully updated.' }
        format.json { render :show, status: :ok, location: @etude }
      else
        format.html { render :edit }
        format.json { render json: @etude.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etudes/1
  # DELETE /etudes/1.json
  def destroy
    @etude.destroy
    respond_to do |format|
      format.html { redirect_to etudes_url, notice: 'Etude was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etude
      @etude = Etude.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def etude_params
      params.require(:etude).permit(:SecteurEtude, :Niveau, :DateDebut, :DateComplition, :Client_id_id, :Institution_id_id)
    end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:Nom, :Adresse_id_id)
    end
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employeurs_helper.rb
module EmployeursHelper
end

app/helpers/enfants_helper.rb
module EnfantsHelper
end

app/helpers/etat_civils_helper.rb
module EtatCivilsHelper
end

app/helpers/etudes_helper.rb
module EtudesHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= form_with(model: institution, local: true) do |form| %>
  <% if institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nom %>
    <%= form.text_field :Nom, id: :institution_Nom %>
  </div>

  <div class="field">
    <%= form.label :Adresse_id_id %>
    <%= form.text_field :Adresse_id_id, id: :institution_Adresse_id_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Institutions</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Adresse</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.Nom %></td>
        <td><%= institution.Adresse_id %></td>
        <td><%= link_to 'Show', institution %></td>
        <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
        <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @institution.Nom %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @institution.Adresse_id %>
</p>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>