config/routes.rb
Rails.application.routes.draw do

  resources :etat_civils
  resources :client_etat_civils
  resources :employeurs
  resources :adresses
  resources :institutions
  resources :etudes
  resources :enfants
  resources :clients
  root 'clients#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adresse.rb
class Adresse < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :Adresse_id
end

app/models/client_etat_civil.rb
class ClientEtatCivil < ApplicationRecord
  belongs_to :Client_id
  belongs_to :EtatCivil_id
end

app/models/client_has_conjoint.rb
class ClientHasConjoint < ApplicationRecord
  belongs_to :Client_id
  belongs_to :Client_conjoint_id
end

app/models/client_has_employeur.rb
class ClientHasEmployeur < ApplicationRecord
  belongs_to :Client_id
  belongs_to :Employeur_id
end

app/models/client_has_enfant.rb
class ClientHasEnfant < ApplicationRecord
  belongs_to :Enfant_id
  belongs_to :Client_id
end

app/models/employeur.rb
class Employeur < ApplicationRecord
  belongs_to :Adresse_id
end

app/models/enfant.rb
class Enfant < ApplicationRecord
end

app/models/etat_civil.rb
class EtatCivil < ApplicationRecord
end

app/models/etude.rb
class Etude < ApplicationRecord
  belongs_to :Client_id
  belongs_to :Institution_id
end

app/models/institution.rb
class Institution < ApplicationRecord
  belongs_to :Adresse_id
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:Prenom, :Nom, :DateNaissance, :NAS, :Adresse_id_id, :NombreEnfants, :CompteTaxesProprietaire)
    end
end

app/controllers/enfants_controller.rb
class EnfantsController < ApplicationController
  before_action :set_enfant, only: [:show, :edit, :update, :destroy]

  # GET /enfants
  # GET /enfants.json
  def index
    @enfants = Enfant.all
  end

  # GET /enfants/1
  # GET /enfants/1.json
  def show
  end

  # GET /enfants/new
  def new
    @enfant = Enfant.new
  end

  # GET /enfants/1/edit
  def edit
  end

  # POST /enfants
  # POST /enfants.json
  def create
    @enfant = Enfant.new(enfant_params)

    respond_to do |format|
      if @enfant.save
        format.html { redirect_to @enfant, notice: 'Enfant was successfully created.' }
        format.json { render :show, status: :created, location: @enfant }
      else
        format.html { render :new }
        format.json { render json: @enfant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enfants/1
  # PATCH/PUT /enfants/1.json
  def update
    respond_to do |format|
      if @enfant.update(enfant_params)
        format.html { redirect_to @enfant, notice: 'Enfant was successfully updated.' }
        format.json { render :show, status: :ok, location: @enfant }
      else
        format.html { render :edit }
        format.json { render json: @enfant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enfants/1
  # DELETE /enfants/1.json
  def destroy
    @enfant.destroy
    respond_to do |format|
      format.html { redirect_to enfants_url, notice: 'Enfant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enfant
      @enfant = Enfant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enfant_params
      params.require(:enfant).permit(:Nom, :Prenom, :DateNaissance)
    end
end

app/controllers/etudes_controller.rb
class EtudesController < ApplicationController
  before_action :set_etude, only: [:show, :edit, :update, :destroy]

  # GET /etudes
  # GET /etudes.json
  def index
    @etudes = Etude.all
  end

  # GET /etudes/1
  # GET /etudes/1.json
  def show
  end

  # GET /etudes/new
  def new
    @etude = Etude.new
  end

  # GET /etudes/1/edit
  def edit
  end

  # POST /etudes
  # POST /etudes.json
  def create
    @etude = Etude.new(etude_params)

    respond_to do |format|
      if @etude.save
        format.html { redirect_to @etude, notice: 'Etude was successfully created.' }
        format.json { render :show, status: :created, location: @etude }
      else
        format.html { render :new }
        format.json { render json: @etude.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /etudes/1
  # PATCH/PUT /etudes/1.json
  def update
    respond_to do |format|
      if @etude.update(etude_params)
        format.html { redirect_to @etude, notice: 'Etude was successfully updated.' }
        format.json { render :show, status: :ok, location: @etude }
      else
        format.html { render :edit }
        format.json { render json: @etude.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etudes/1
  # DELETE /etudes/1.json
  def destroy
    @etude.destroy
    respond_to do |format|
      format.html { redirect_to etudes_url, notice: 'Etude was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etude
      @etude = Etude.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def etude_params
      params.require(:etude).permit(:SecteurEtude, :Niveau, :DateDebut, :DateComplition, :Client_id_id, :Institution_id_id)
    end
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employeurs_helper.rb
module EmployeursHelper
end

app/helpers/enfants_helper.rb
module EnfantsHelper
end

app/helpers/etat_civils_helper.rb
module EtatCivilsHelper
end

app/helpers/etudes_helper.rb
module EtudesHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Prenom %>
    <%= form.text_field :Prenom, id: :client_Prenom %>
  </div>

  <div class="field">
    <%= form.label :Nom %>
    <%= form.text_field :Nom, id: :client_Nom %>
  </div>

  <div class="field">
    <%= form.label :DateNaissance %>
    <%= form.datetime_select :DateNaissance, id: :client_DateNaissance %>
  </div>

  <div class="field">
    <%= form.label :NAS %>
    <%= form.text_field :NAS, id: :client_NAS %>
  </div>

  <div class="field">
    <%= form.label :Adresse_id_id %>
    <%= form.text_field :Adresse_id_id, id: :client_Adresse_id_id %>
  </div>

  <div class="field">
    <%= form.label :NombreEnfants %>
    <%= form.number_field :NombreEnfants, id: :client_NombreEnfants %>
  </div>

  <div class="field">
    <%= form.label :CompteTaxesProprietaire %>
    <%= form.number_field :CompteTaxesProprietaire, id: :client_CompteTaxesProprietaire %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Prenom</th>
      <th>Nom</th>
      <th>Datenaissance</th>
      <th>Nas</th>
      <th>Adresse</th>
      <th>Nombreenfants</th>
      <th>Comptetaxesproprietaire</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.Prenom %></td>
        <td><%= client.Nom %></td>
        <td><%= client.DateNaissance %></td>
        <td><%= client.NAS %></td>
        <td><%= client.Adresse_id %></td>
        <td><%= client.NombreEnfants %></td>
        <td><%= client.CompteTaxesProprietaire %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prenom:</strong>
  <%= @client.Prenom %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @client.Nom %>
</p>

<p>
  <strong>Datenaissance:</strong>
  <%= @client.DateNaissance %>
</p>

<p>
  <strong>Nas:</strong>
  <%= @client.NAS %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @client.Adresse_id %>
</p>

<p>
  <strong>Nombreenfants:</strong>
  <%= @client.NombreEnfants %>
</p>

<p>
  <strong>Comptetaxesproprietaire:</strong>
  <%= @client.CompteTaxesProprietaire %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/enfants/_form.html.erb
<%= form_with(model: enfant, local: true) do |form| %>
  <% if enfant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enfant.errors.count, "error") %> prohibited this enfant from being saved:</h2>

      <ul>
      <% enfant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nom %>
    <%= form.text_field :Nom, id: :enfant_Nom %>
  </div>

  <div class="field">
    <%= form.label :Prenom %>
    <%= form.text_field :Prenom, id: :enfant_Prenom %>
  </div>

  <div class="field">
    <%= form.label :DateNaissance %>
    <%= form.datetime_select :DateNaissance, id: :enfant_DateNaissance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enfants/edit.html.erb
<h1>Editing Enfant</h1>

<%= render 'form', enfant: @enfant %>

<%= link_to 'Show', @enfant %> |
<%= link_to 'Back', enfants_path %>

app/views/enfants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enfants</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Datenaissance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enfants.each do |enfant| %>
      <tr>
        <td><%= enfant.Nom %></td>
        <td><%= enfant.Prenom %></td>
        <td><%= enfant.DateNaissance %></td>
        <td><%= link_to 'Show', enfant %></td>
        <td><%= link_to 'Edit', edit_enfant_path(enfant) %></td>
        <td><%= link_to 'Destroy', enfant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enfant', new_enfant_path %>

app/views/enfants/new.html.erb
<h1>New Enfant</h1>

<%= render 'form', enfant: @enfant %>

<%= link_to 'Back', enfants_path %>

app/views/enfants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @enfant.Nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @enfant.Prenom %>
</p>

<p>
  <strong>Datenaissance:</strong>
  <%= @enfant.DateNaissance %>
</p>

<%= link_to 'Edit', edit_enfant_path(@enfant) %> |
<%= link_to 'Back', enfants_path %>

app/views/etudes/_form.html.erb
<%= form_with(model: etude, local: true) do |form| %>
  <% if etude.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(etude.errors.count, "error") %> prohibited this etude from being saved:</h2>

      <ul>
      <% etude.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :SecteurEtude %>
    <%= form.text_field :SecteurEtude, id: :etude_SecteurEtude %>
  </div>

  <div class="field">
    <%= form.label :Niveau %>
    <%= form.text_field :Niveau, id: :etude_Niveau %>
  </div>

  <div class="field">
    <%= form.label :DateDebut %>
    <%= form.datetime_select :DateDebut, id: :etude_DateDebut %>
  </div>

  <div class="field">
    <%= form.label :DateComplition %>
    <%= form.datetime_select :DateComplition, id: :etude_DateComplition %>
  </div>

  <div class="field">
    <%= form.label :Client_id_id %>
    <%= form.text_field :Client_id_id, id: :etude_Client_id_id %>
  </div>

  <div class="field">
    <%= form.label :Institution_id_id %>
    <%= form.text_field :Institution_id_id, id: :etude_Institution_id_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/etudes/edit.html.erb
<h1>Editing Etude</h1>

<%= render 'form', etude: @etude %>

<%= link_to 'Show', @etude %> |
<%= link_to 'Back', etudes_path %>

app/views/etudes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Etudes</h1>

<table>
  <thead>
    <tr>
      <th>Secteuretude</th>
      <th>Niveau</th>
      <th>Datedebut</th>
      <th>Datecomplition</th>
      <th>Client</th>
      <th>Institution</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @etudes.each do |etude| %>
      <tr>
        <td><%= etude.SecteurEtude %></td>
        <td><%= etude.Niveau %></td>
        <td><%= etude.DateDebut %></td>
        <td><%= etude.DateComplition %></td>
        <td><%= etude.Client_id %></td>
        <td><%= etude.Institution_id %></td>
        <td><%= link_to 'Show', etude %></td>
        <td><%= link_to 'Edit', edit_etude_path(etude) %></td>
        <td><%= link_to 'Destroy', etude, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Etude', new_etude_path %>

app/views/etudes/new.html.erb
<h1>New Etude</h1>

<%= render 'form', etude: @etude %>

<%= link_to 'Back', etudes_path %>

app/views/etudes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Secteuretude:</strong>
  <%= @etude.SecteurEtude %>
</p>

<p>
  <strong>Niveau:</strong>
  <%= @etude.Niveau %>
</p>

<p>
  <strong>Datedebut:</strong>
  <%= @etude.DateDebut %>
</p>

<p>
  <strong>Datecomplition:</strong>
  <%= @etude.DateComplition %>
</p>

<p>
  <strong>Client:</strong>
  <%= @etude.Client_id %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @etude.Institution_id %>
</p>

<%= link_to 'Edit', edit_etude_path(@etude) %> |
<%= link_to 'Back', etudes_path %>