config/routes.rb
Rails.application.routes.draw do

  resources :etat_civils
  resources :client_etat_civils
  resources :employeurs
  resources :adresses
  resources :institutions
  resources :etudes
  resources :enfants
  resources :clients
  root 'clients#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adresse.rb
class Adresse < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :Adresse_id
end

app/models/client_etat_civil.rb
class ClientEtatCivil < ApplicationRecord
  belongs_to :Client_id
  belongs_to :EtatCivil_id
end

app/models/client_has_conjoint.rb
class ClientHasConjoint < ApplicationRecord
  belongs_to :Client_id
  belongs_to :Client_conjoint_id
end

app/models/client_has_employeur.rb
class ClientHasEmployeur < ApplicationRecord
  belongs_to :Client_id
  belongs_to :Employeur_id
end

app/models/client_has_enfant.rb
class ClientHasEnfant < ApplicationRecord
  belongs_to :Enfant_id
  belongs_to :Client_id
end

app/models/employeur.rb
class Employeur < ApplicationRecord
  belongs_to :Adresse_id
end

app/models/enfant.rb
class Enfant < ApplicationRecord
end

app/models/etat_civil.rb
class EtatCivil < ApplicationRecord
end

app/models/etude.rb
class Etude < ApplicationRecord
  belongs_to :Client_id
  belongs_to :Institution_id
end

app/models/institution.rb
class Institution < ApplicationRecord
  belongs_to :Adresse_id
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:Prenom, :Nom, :DateNaissance, :NAS, :Adresse_id_id, :NombreEnfants, :CompteTaxesProprietaire)
    end
end

app/controllers/employeurs_controller.rb
class EmployeursController < ApplicationController
  before_action :set_employeur, only: [:show, :edit, :update, :destroy]

  # GET /employeurs
  # GET /employeurs.json
  def index
    @employeurs = Employeur.all
  end

  # GET /employeurs/1
  # GET /employeurs/1.json
  def show
  end

  # GET /employeurs/new
  def new
    @employeur = Employeur.new
  end

  # GET /employeurs/1/edit
  def edit
  end

  # POST /employeurs
  # POST /employeurs.json
  def create
    @employeur = Employeur.new(employeur_params)

    respond_to do |format|
      if @employeur.save
        format.html { redirect_to @employeur, notice: 'Employeur was successfully created.' }
        format.json { render :show, status: :created, location: @employeur }
      else
        format.html { render :new }
        format.json { render json: @employeur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employeurs/1
  # PATCH/PUT /employeurs/1.json
  def update
    respond_to do |format|
      if @employeur.update(employeur_params)
        format.html { redirect_to @employeur, notice: 'Employeur was successfully updated.' }
        format.json { render :show, status: :ok, location: @employeur }
      else
        format.html { render :edit }
        format.json { render json: @employeur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employeurs/1
  # DELETE /employeurs/1.json
  def destroy
    @employeur.destroy
    respond_to do |format|
      format.html { redirect_to employeurs_url, notice: 'Employeur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employeur
      @employeur = Employeur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employeur_params
      params.require(:employeur).permit(:nom, :Adresse_id_id)
    end
end

app/controllers/etudes_controller.rb
class EtudesController < ApplicationController
  before_action :set_etude, only: [:show, :edit, :update, :destroy]

  # GET /etudes
  # GET /etudes.json
  def index
    @etudes = Etude.all
  end

  # GET /etudes/1
  # GET /etudes/1.json
  def show
  end

  # GET /etudes/new
  def new
    @etude = Etude.new
  end

  # GET /etudes/1/edit
  def edit
  end

  # POST /etudes
  # POST /etudes.json
  def create
    @etude = Etude.new(etude_params)

    respond_to do |format|
      if @etude.save
        format.html { redirect_to @etude, notice: 'Etude was successfully created.' }
        format.json { render :show, status: :created, location: @etude }
      else
        format.html { render :new }
        format.json { render json: @etude.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /etudes/1
  # PATCH/PUT /etudes/1.json
  def update
    respond_to do |format|
      if @etude.update(etude_params)
        format.html { redirect_to @etude, notice: 'Etude was successfully updated.' }
        format.json { render :show, status: :ok, location: @etude }
      else
        format.html { render :edit }
        format.json { render json: @etude.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etudes/1
  # DELETE /etudes/1.json
  def destroy
    @etude.destroy
    respond_to do |format|
      format.html { redirect_to etudes_url, notice: 'Etude was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etude
      @etude = Etude.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def etude_params
      params.require(:etude).permit(:SecteurEtude, :Niveau, :DateDebut, :DateComplition, :Client_id_id, :Institution_id_id)
    end
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employeurs_helper.rb
module EmployeursHelper
end

app/helpers/enfants_helper.rb
module EnfantsHelper
end

app/helpers/etat_civils_helper.rb
module EtatCivilsHelper
end

app/helpers/etudes_helper.rb
module EtudesHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/employeurs/_form.html.erb
<%= form_with(model: employeur, local: true) do |form| %>
  <% if employeur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employeur.errors.count, "error") %> prohibited this employeur from being saved:</h2>

      <ul>
      <% employeur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nom %>
    <%= form.text_field :nom, id: :employeur_nom %>
  </div>

  <div class="field">
    <%= form.label :Adresse_id_id %>
    <%= form.text_field :Adresse_id_id, id: :employeur_Adresse_id_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employeurs/edit.html.erb
<h1>Editing Employeur</h1>

<%= render 'form', employeur: @employeur %>

<%= link_to 'Show', @employeur %> |
<%= link_to 'Back', employeurs_path %>

app/views/employeurs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employeurs</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Adresse</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employeurs.each do |employeur| %>
      <tr>
        <td><%= employeur.nom %></td>
        <td><%= employeur.Adresse_id %></td>
        <td><%= link_to 'Show', employeur %></td>
        <td><%= link_to 'Edit', edit_employeur_path(employeur) %></td>
        <td><%= link_to 'Destroy', employeur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employeur', new_employeur_path %>

app/views/employeurs/new.html.erb
<h1>New Employeur</h1>

<%= render 'form', employeur: @employeur %>

<%= link_to 'Back', employeurs_path %>

app/views/employeurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @employeur.nom %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @employeur.Adresse_id %>
</p>

<%= link_to 'Edit', edit_employeur_path(@employeur) %> |
<%= link_to 'Back', employeurs_path %>