config/routes.rb
Rails.application.routes.draw do

  resources :etat_civils
  resources :client_etat_civils
  resources :employeurs
  resources :adresses
  resources :institutions
  resources :etudes
  resources :enfants
  resources :clients
  root 'clients#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adresse.rb
class Adresse < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :Adresse_id
end

app/models/client_etat_civil.rb
class ClientEtatCivil < ApplicationRecord
  belongs_to :Client_id
  belongs_to :EtatCivil_id
end

app/models/client_has_conjoint.rb
class ClientHasConjoint < ApplicationRecord
  belongs_to :Client_id
  belongs_to :Client_conjoint_id
end

app/models/client_has_employeur.rb
class ClientHasEmployeur < ApplicationRecord
  belongs_to :Client_id
  belongs_to :Employeur_id
end

app/models/client_has_enfant.rb
class ClientHasEnfant < ApplicationRecord
  belongs_to :Enfant_id
  belongs_to :Client_id
end

app/models/employeur.rb
class Employeur < ApplicationRecord
  belongs_to :Adresse_id
end

app/models/enfant.rb
class Enfant < ApplicationRecord
end

app/models/etat_civil.rb
class EtatCivil < ApplicationRecord
end

app/models/etude.rb
class Etude < ApplicationRecord
  belongs_to :Client_id
  belongs_to :Institution_id
end

app/models/institution.rb
class Institution < ApplicationRecord
  belongs_to :Adresse_id
end

app/controllers/adresses_controller.rb
class AdressesController < ApplicationController
  before_action :set_adress, only: [:show, :edit, :update, :destroy]

  # GET /adresses
  # GET /adresses.json
  def index
    @adresses = Adresse.all
  end

  # GET /adresses/1
  # GET /adresses/1.json
  def show
  end

  # GET /adresses/new
  def new
    @adress = Adresse.new
  end

  # GET /adresses/1/edit
  def edit
  end

  # POST /adresses
  # POST /adresses.json
  def create
    @adress = Adresse.new(adress_params)

    respond_to do |format|
      if @adress.save
        format.html { redirect_to @adress, notice: 'Adresse was successfully created.' }
        format.json { render :show, status: :created, location: @adress }
      else
        format.html { render :new }
        format.json { render json: @adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adresses/1
  # PATCH/PUT /adresses/1.json
  def update
    respond_to do |format|
      if @adress.update(adress_params)
        format.html { redirect_to @adress, notice: 'Adresse was successfully updated.' }
        format.json { render :show, status: :ok, location: @adress }
      else
        format.html { render :edit }
        format.json { render json: @adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adresses/1
  # DELETE /adresses/1.json
  def destroy
    @adress.destroy
    respond_to do |format|
      format.html { redirect_to adresses_url, notice: 'Adresse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adress
      @adress = Adresse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adress_params
      params.require(:adress).permit(:NumeroCivique, :Rue, :CodePostal, :Ville, :Province)
    end
end

app/controllers/etudes_controller.rb
class EtudesController < ApplicationController
  before_action :set_etude, only: [:show, :edit, :update, :destroy]

  # GET /etudes
  # GET /etudes.json
  def index
    @etudes = Etude.all
  end

  # GET /etudes/1
  # GET /etudes/1.json
  def show
  end

  # GET /etudes/new
  def new
    @etude = Etude.new
  end

  # GET /etudes/1/edit
  def edit
  end

  # POST /etudes
  # POST /etudes.json
  def create
    @etude = Etude.new(etude_params)

    respond_to do |format|
      if @etude.save
        format.html { redirect_to @etude, notice: 'Etude was successfully created.' }
        format.json { render :show, status: :created, location: @etude }
      else
        format.html { render :new }
        format.json { render json: @etude.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /etudes/1
  # PATCH/PUT /etudes/1.json
  def update
    respond_to do |format|
      if @etude.update(etude_params)
        format.html { redirect_to @etude, notice: 'Etude was successfully updated.' }
        format.json { render :show, status: :ok, location: @etude }
      else
        format.html { render :edit }
        format.json { render json: @etude.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etudes/1
  # DELETE /etudes/1.json
  def destroy
    @etude.destroy
    respond_to do |format|
      format.html { redirect_to etudes_url, notice: 'Etude was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etude
      @etude = Etude.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def etude_params
      params.require(:etude).permit(:SecteurEtude, :Niveau, :DateDebut, :DateComplition, :Client_id_id, :Institution_id_id)
    end
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employeurs_helper.rb
module EmployeursHelper
end

app/helpers/enfants_helper.rb
module EnfantsHelper
end

app/helpers/etat_civils_helper.rb
module EtatCivilsHelper
end

app/helpers/etudes_helper.rb
module EtudesHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/adresses/_form.html.erb
<%= form_with(model: adress, local: true) do |form| %>
  <% if adress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adress.errors.count, "error") %> prohibited this adress from being saved:</h2>

      <ul>
      <% adress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :NumeroCivique %>
    <%= form.text_field :NumeroCivique, id: :adress_NumeroCivique %>
  </div>

  <div class="field">
    <%= form.label :Rue %>
    <%= form.text_field :Rue, id: :adress_Rue %>
  </div>

  <div class="field">
    <%= form.label :CodePostal %>
    <%= form.text_field :CodePostal, id: :adress_CodePostal %>
  </div>

  <div class="field">
    <%= form.label :Ville %>
    <%= form.text_field :Ville, id: :adress_Ville %>
  </div>

  <div class="field">
    <%= form.label :Province %>
    <%= form.text_field :Province, id: :adress_Province %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/adresses/edit.html.erb
<h1>Editing Adress</h1>

<%= render 'form', adress: @adress %>

<%= link_to 'Show', @adress %> |
<%= link_to 'Back', adresses_path %>

app/views/adresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adresses</h1>

<table>
  <thead>
    <tr>
      <th>Numerocivique</th>
      <th>Rue</th>
      <th>Codepostal</th>
      <th>Ville</th>
      <th>Province</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adresses.each do |adress| %>
      <tr>
        <td><%= adress.NumeroCivique %></td>
        <td><%= adress.Rue %></td>
        <td><%= adress.CodePostal %></td>
        <td><%= adress.Ville %></td>
        <td><%= adress.Province %></td>
        <td><%= link_to 'Show', adress %></td>
        <td><%= link_to 'Edit', edit_adress_path(adress) %></td>
        <td><%= link_to 'Destroy', adress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adress', new_adress_path %>

app/views/adresses/new.html.erb
<h1>New Adress</h1>

<%= render 'form', adress: @adress %>

<%= link_to 'Back', adresses_path %>

app/views/adresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numerocivique:</strong>
  <%= @adress.NumeroCivique %>
</p>

<p>
  <strong>Rue:</strong>
  <%= @adress.Rue %>
</p>

<p>
  <strong>Codepostal:</strong>
  <%= @adress.CodePostal %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @adress.Ville %>
</p>

<p>
  <strong>Province:</strong>
  <%= @adress.Province %>
</p>

<%= link_to 'Edit', edit_adress_path(@adress) %> |
<%= link_to 'Back', adresses_path %>